language: python
python:
  - "2.7"
matrix:
  include:
    # Test on pypy without coverage, because it's unnecessary and very slow.
    - python: "pypy"
      env: PYPY_VERSION="4.0.1" NO_COVERAGE=1
    # Test against the lowest version of Twisted that we claim to support
    - python: "2.7"
      env: TWISTED_VERSION="Twisted==15.3.0"
before_install:
  - if [ ! -z "$PYPY_VERSION" ]; then source utils/setup-pypy-travis.sh; fi
install:
  - "pip install ${TWISTED_VERSION}"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=junebug"; else COVERAGE_CMD=""; fi
  - $COVERAGE_CMD `which trial` junebug
after_success:
  - coveralls
deploy:
  provider: pypi
  user: praekelt.org
  distributions: "sdist bdist_wheel"
  password:
    secure: "Nzfr8XnzfTr2NWD4oJjkH4CQG3PXH+Te2lqJvGTxsrXn8SjZZ6NatgIpFBJliZeM3lE1wO4nWuydyGKkaUxCahFR6qbEiqVGtCl14nta9UTJ/LhcCpNB94JCov0Ye3mtM7TzfNb5mF7Y6/xfjeLywGKH6hfHEdCemQbfp5y4R734LE0c6mVQYU9O6DtRNW5TlwMFUWJgWEVfJJdAdyZD3SMec93oQntuO7RvA5LxXmy3htHaQ6xeJc3ZFxaIMuvyfclVH4ZeXT1Bx9NL58OIhbp0SorkCHWFt5zlqInzmQsfj3i5t5okOFncGh1LvafNGWWWWciwZgCQ1y7+dH4Fz/SiaDw+Gz/tK2YTZsG0fEMXH8CtLOUW7zWuqRUDmWms6pX3Jjp8RyyVcVoKUwoKKf2K3u7LbZqIEE+U/sGQn0nsFPAM8YwYiH7SRgVK7BYzQivTxJSXdy7PZtqY9G9zOZyQEtMjxzmHOmUQQHawVKWJg+65bKeD6ttrTcZOiqjYohrgFsVT91Oe13jH9YaFDT3uHA60NoHsoDSnAVdUZto4WjUm3z85SLyytOIZRlsv3tb3ViEVHFgf+YBgakf9ia+HplGV+7lIf1V6ImKaFZc3ohXcRZockYXBt4kF3BQuhevZZLyccjGr7ZRCYfoTSsoKR8z2ehVYdHspVyajCGM="
  on:
    tags: true
    all_branches: true
